### ISSUE TITLE
You can try creating ADs Injection Tool for Android APKs

### ISSUE THREAD

**Issue by gomez9xmario** [T5ive/Tools-Injector-Mod-Menu#1]
You can try creating ADs Injection Tool for Android APKs

**Comment by T5ive** [comment]
I think the ad injection tool is easy.
But now I have to go to the midterm exam See you after the 13th

**Comment by gomez9xmario** [comment]
> Tôi nghĩ rằng công cụ tiêm quảng cáo rất dễ dàng.
> Nhưng giờ em phải đi thi giữa kì Hẹn gặp lại các bạn sau ngày 13



> I think the ad injection tool is easy.
> But now I have to go to the midterm exam See you after the 13th

Hope you will be interested in this project.
This is AndnixSH's previous project but he stopped you can refer to .I want to hire you with this project, how much does it cost?
https://github.com/AndnixSH/AdsTool

**Comment by gomez9xmario** [comment]
> I think the ad injection tool is easy.
> But now I have to go to the midterm exam See you after the 13th

Hope you will be interested in this project.
This is AndnixSH's previous project but he stopped you can refer to .I want to hire you with this project, how much does it cost?
https://github.com/AndnixSH/AdsTool

**Comment by T5ive** [comment]
> I want to hire you with this project, how much does it cost?

Free!
Any project from me is always free.
