### ISSUE TITLE
Toast is not appearing

### ISSUE THREAD

**Issue by samsix56** [T5ive/Tools-Injector-Mod-Menu#2]
Hello Sir,
The Tool is working perfectly fine but the only problem here is that toast is not appearing in the game.

**Comment by T5ive** [comment]
uncheck "Remove modified files"
after compile press "Temp modify directory"
in folder "jni" copy "Toast.h", & Log to me
If possible, take a screenshot of the main settings as well.

**Comment by samsix56** [comment]
![Untitled](https://user-images.githubusercontent.com/79263647/108465531-34bff680-72a8-11eb-8040-75785ecf3925.jpg)

**Comment by samsix56** [comment]
#ifndef TFIVE_IL2CPP_MENU_TOAST_H
#define TFIVE_IL2CPP_MENU_TOAST_H

extern "C" {
JNIEXPORT void JNICALL
Java_com_tfive_MainActivity_Toast(JNIEnv *env, jclass obj, jobject context) {
     MakeToast(env, context, OBFUSCATE("ANDROPALACE.ORG"), Toast::LENGTH_LONG);

}
}
#endif

**Comment by samsix56** [comment]
i have attached a main settings screenshot and copied entire content of Toast.h file

**Comment by T5ive** [comment]
It seems that the problem is not with my tools.
Maybe at the emulator or the game.
Or maybe you should contact LGLTeam.
