### ISSUE TITLE
Add more features and crashes

### ISSUE THREAD

**Issue by SliceCast** [T5ive/Tools-Injector-Mod-Menu#4]
Hello, my name is Slice Cast. I have tested your tools, it's pretty great, but they're some crashes, which I really don't know. It could be smali, could be main.cpp, could be manifest.xml, who knows. 

Also, if you want more features, if you have discord
My username: SliceCast#1558

I want to help you with some hooks and things to add to your tool to be more easier than use.

**Comment by T5ive** [comment]
version 1.4.2 should be fine
the string features will add soon
